name: Build and Test

on:
  pull_request:
    branches: [ main ]

env: 
  AWS_REGION: ap-northeast-1

jobs:
  test:
    name: Test stack
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”§ Checkout branch
        uses: actions/checkout@v2
      - name: ğŸ“¦ Setup dependencies
        run: npm ci
      - name: ğŸ”§ Build
        run: npm run build
      - name: ğŸ”« Jest
        run: npm run test
      - name: CDK Diff Check
        id: cdk_diff
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          diff_out=$(npm run cdk:diff)
          # ã‚¨ã‚¹ã‚±ãƒ¼ãƒ—å‡¦ç†
          diff_out="${diff_out//$'\n'/\\n}"
          echo $diff_out
          echo "::set-output name=std_out::$diff_out"
      - name: Echo Stdouts
        run: echo "${{ steps.cdk_diff.outputs.std_out }}"
      - name: Echo other
        run: echo "{{jobs.cdk_diff.outputs}}""