name: Build and Test

on:
  pull_request:
    branches: [ main ]

env: 
  AWS_REGION: ap-northeast-1

jobs:
  test:
    name: Test stack
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ”§ Checkout branch
        uses: actions/checkout@v2
      - name: ðŸ“¦ Setup dependencies
        run: npm ci
      - name: ðŸ”§ Build
        run: npm run build
      - name: ðŸ”« Jest
        run: npm run test
      - name: CDK Diff Check
        id: cdk_diff
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npm run cdk:diff --ci  &> diff.txt
          less diff.txt
      # read from file and assign to outputs object
      # - name: Read and assign
      #   id: output_test
      #   run: |
      #     input_file="diff.txt"
      #     while read line
      #     do
      #       file_text=$line
      #     done < "$input_file"
      #     echo ::set-output name=new_value::$file_text
      # # test to see if done correctly - should echo "value"
      # - run: echo ${â€‹â€‹â€‹â€‹{â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹ steps.output_test.outputs.new_value }â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹}â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹
      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            This comment was written by a bot!
          reactions: rocket
      # ç”Ÿæˆã—ãŸtxtã‚’ãƒ‘ãƒ¼ã‚¹
      - id: get-comment-body
        run: |
          body="$(cat diff.txt)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"
      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          reactions: rocket